inputs_def:
  - handle: token
    description: Input
    json_schema:
      contentMediaType: oomol/secret
      type: string
    value: ${{OO_SECRET:SiliconFlow,SiliconFlow,SILICON_FLOW_TOKEN}}
  - handle: model
    json_schema:
      enum:
        - stabilityai/stable-diffusion-3-5-large
        - stabilityai/stable-diffusion-3-5-large-turbo
        - stabilityai/stable-diffusion-3-medium
        - black-forest-labs/FLUX.1-dev
      ui:options:
        labels:
          - stabilityai/stable-diffusion-3-5-large
          - stabilityai/stable-diffusion-3-5-large-turbo
          - stabilityai/stable-diffusion-3-medium
          - black-forest-labs/FLUX.1-dev
    value: ""
  - handle: prompt
    json_schema:
      type: string
      ui:widget: text
    nullable: false
  - handle: negative_prompt
    json_schema:
      type: string
      ui:widget: text
    value:
    nullable: true
  - handle: image_size
    json_schema:
      type: object
      additionalProperties: false
      properties:
        width:
          type: number
        height:
          type: number
    value:
    nullable: true
  - handle: batch_size
    json_schema:
      type: number
    value:
    nullable: true
  - handle: seed
    json_schema:
      type: number
    value:
    nullable: true
  - handle: num_inference_steps
    json_schema:
      type: number
    value:
    nullable: true
  - handle: guidance_scale
    json_schema:
      type: number
    value:
    nullable: true
  - handle: prompt_enhancement
    json_schema:
      type: number
    value:
    nullable: true
outputs_def:
  - handle: output
    description: Output
    json_schema:
      type: string
ui:
  default_width: 450
executor:
  name: nodejs
  options:
    spawn: false
    entry: main.ts
title: Image Generation
icon: ":fa6-solid:image:"
